# Generated by Django 5.2.3 on 2025-07-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Handler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecredentials',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='googlecredentials',
            name='client_secret',
        ),
    ]
